#!/bin/sh

export VENV_ROOT=`pwd`
export DJANGO_SETTINGS_MODULE=esxsnmp.settings

# create the virtualenv
virtualenv --prompt="(django-kiosk)" .
. bin/activate

# XXX(jdugan) FreeBSD hack look for headers and libraries in /usr/local
# ObRant: WTF is with distutils/setuputils/pip not offerring a way to handle this?!?
# ObRantRant: OR maybe it's crappy behaviour on the part of pysqlite?  dunno
if [ x`uname` = x"FreeBSD" ]; then
    echo patching pysqlite to build under FreeBSD
    pip install --no-install pysqlite
    echo 'include_dirs=/usr/local/include' >> build/pysqlite/setup.cfg
    echo 'library_dirs=/usr/local/lib' >> build/pysqlite/setup.cfg
fi

pip install -r requirements.txt

cat <<EOF > django-kiosk.env
export DJANGO_SETTINGS_MODULE="kiosk_example.settings"
. ${VENV_ROOT}/bin/activate
EOF

echo environment variables and activation put in ${VENV_ROOT}/django-kiosk.env:
cat ${VENV_ROOT}/django-kiosk.env
echo run: source ${VENV_ROOT}/django-kiosk.env to set up your environment for development
